version: '3.8'

services:
  db:
    image: postgres:17
    env_file:
      - .env  # Подключаем файл с переменными
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U barter_user -d barter_db"]
      interval: 1s
      timeout: 1s
      retries: 1

  web:
    build: .
    environment:
      DATABASE_URL: ${DATABASE_URL}
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

volumes:
  postgres_data:
