version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: barter_db
      POSTGRES_USER: barter_user
      POSTGRES_PASSWORD: barter_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U barter_user -d barter_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    environment:
      DATABASE_URL: postgres://barter_user:barter_password@db:5432/barter_db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

volumes:
  postgres_data: